name: accordion
description: Accordion widget to display a list of expandable items with opening/closing and scroll-into-view animations.
version: 2.0.0
homepage: https://www.vulcansoft.com
repository: https://github.com/GotJimmy/accordion

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.4"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  scroll_to_index: ^2.0.0

flutter:
  uses-material-design: true
